version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: foodapi-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-food}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-food}"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    container_name: foodapi-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-food}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DEBUG: "false"
      JWT_SECRET: ${JWT_SECRET:-devsecret}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
      ADMIN_PHONE: ${ADMIN_PHONE:-0000000000}
      ADMIN_AVATAR_URL: ${ADMIN_AVATAR_URL:-}
    ports:
      - "8000:8000"

volumes:
  db_data:


